#!/usr/bin/env node

var connect = require('connect'),
    cli = require('cli').enable('version');

cli.setApp('sws', '0.1.0');
    
cli.parse({
    port:  ['p', 'Listen on this port', 'number', 8080],
    serve: ['s', 'Serve static files from PATH', 'path', '.']
});

cli.main(function(args, options) {
  connect.createServer(
    //this allows for different versions of connect
    connect[connect.version.split('.').shift()>0?'static':'staticProvider']
    (options.serve)
  ).listen(options.port);
  console.log("SWS server listening at http://127.0.0.1:%d/", options.port);
});
