#!/usr/bin/env node

var connect = require('connect'),
    cli = require('cli').enable('version');

process.title = "sws";

cli.setApp('sws', '0.0.2');
    
cli.parse({
    port:  ['p', 'Listen on this port', 'number', 8080],
    dir: ['d', 'Web root directory', 'path', '.']
});

cli.main(function(args, options) {
  connect.createServer(
    //this allows for different versions of connect
    connect[connect.version.split('.').shift()>0?'static':'staticProvider']
    (options.dir)
  ).listen(options.port);
  console.log("SWS server listening at http://127.0.0.1:%d/", options.port);
});
